name: template
description: Flutter architecture template.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #State management
  flutter_bloc:
  hooks_riverpod:

  #Core logic
  get_it:
  dartz:

  # UI
  auto_size_text:
  animations:
  cupertino_icons: ^1.0.0
  logger:

  very_good_analysis:
  reactive_forms:
  freezed_annotation:
  #edvcli
  supercharged:
  #Triage if necessary
  cross_connectivity: ^2.0.1
  built_value:
  get:
  # Local dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  build_runner:


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  lineLength: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: false
    flare_flutter: false
# Add a remote custom package to flutter
#  custom_package:
#    git:
#      url: https://github.com/your-username/custom_package
#      path: packages/custom_package
flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
